### ISSUE TITLE
Additional system statistics

### ISSUE THREAD

**Issue by geoffculp** [Kegbot/kegbot-server#106]
The all-time stats kegweb page could use some additional stats.  I thought it would be useful to have some new info displayed.  Maybe some or all of the following:
1.  Largest overall session and largest drinker session.
2.  "Top 10 sessions"
3.  Keg stats.  Overall Number and total volume stats.
4.  Keg life time stats.  Shortest keg and longest keg
5.  All drinker volume page.  (Expand the "top 10 drinkers" into a separate page with a sorted list of all drinkers)

**Comment by mik3y** [comment]
Bug scrub: No plans to implement this right now. (Long time no see, Geoff - hope you're well!)

**Comment by Philusha1983** [comment]
Hello, I'm following this project on github, I see lot of activity, are you
planning to relaunch it?

**Comment by mik3y** [comment]
Hi @Philusha1983 !

> I see lot of activity, are you planning to relaunch it?

Nothing major to announce right now, just spending a few cycles giving the project some care. You can see a new [milestones list](https://github.com/Kegbot/kegbot-server/milestones) for a very rough idea of some goals.

**Comment by Philusha1983** [comment]
​​
THANKS

*Philip* :)
