### ISSUE TITLE
Support online databases (brewerydb, untappd, etc) for beverage type info

### ISSUE THREAD

**Issue by mik3y** [Kegbot/kegbot-server#159]
The built-in beerdb was intended only to supplement a richer, online, community edited beer database.  We had dreams of building one ourselves, but never got around to it.

Thankfully there are now several good sources of beer data: brewerydb and untappd come to mind, and there are others.

Rough idea of how to do this:
- Create a new interface, `BeerInfoBackend`, in the style of `pykeg.notifications.backends`.
- Add a setting that specifies the site-wide `BeerInfoBackend` implementation (for example `pykeg.beerinfo.backends.brewerydb`).
- Revise the `BeerType` model to take two new optional fields:
  - `beerinfo_backend`: the string name of the backend which created/owns this record
  - `beerinfo_id`: the backend-specific beer id (namespaced to the backend)
  - (a row without these fields indicates a locally-defined beer, eg a homebrew)
- Revise the API autocomplete endpoint to search the beerinfo backend (as as locals)
- Add a celery task to periodically refresh any beers from the upstream backend.

Probably want to sequence this carefully with #157.

(This has been on the TODO list forever.)

**Comment by rnieto18** [comment]
With Untappd's api v4 you should be able to pull in data from untappd using a call to their API.  The request would be 
https://api.untappd.com/v4/beer/info/UNTAPPDBEERID?client_id=CLIENTID&client_secret=CLIENTSECRET  

You should be able to have a button on the add beer page that once you entered the beer id you could click it and it would request the information from untappd (as long as the client id and secret were setup) then map the results to populate the page.  Using this you would be able to get the logo as well as the description, ABV and IBU.  

The same could be done for the brewers section as well.

**Comment by mik3y** [comment]
Closing ancient issues: This never got implemented. State of the world is not promising, as Untappd and Brewerydb are not freely licensed.
