### ISSUE TITLE
FR: Ability to delete a user

### ISSUE THREAD

**Issue by markstubb** [Kegbot/kegbot-server#192]

**Comment by patfreeman** [comment]
I ran through the feature list and took account of what's been done so far.
- [ ] Logically delete (aka disable)
  - [X] User login is disabled
  - [X]  Doesn't show up in drinker list (ie in tablet)
  - [ ]  Maybe disable the drinker stats page & don't linkify the profile
  - [X] Drinks, session contributions, stats, etc, are preserved

I like the fact that the stats page and everything is still visible for disabled drinkers. Kind of nostalgia for those that are gone. 🤷 

- [ ] Actual delete   
  - [ ] Reassign all drinks to "guest"     
    - [ ] Recomputes all stats and sessions
    - [ ] This can be very expensive
  - [ ] Delete all photos (and any other per-user assets down the road)
  - [ ] Disable the account

> As proposed, in both cases the `User` record isn't ever deleted: `disable` is reversible, and for `delete`, it prevents the username from being reclaimed. (We could visit that topic separately, but I haven't thought through what it would mean for other clients like the app.)

For the actual delete process if we go through all the effort to reassign all the drinks and delete all the photos, why wouldn't we just delete the `User`? There is no data left associated to it, so it doesn't have much value. If the `User` is gone and the human returns and wants a new 'kegbot life', they can start fresh with a new registration.
