### ISSUE TITLE
FR - Duplicate Tweets "New Session" & "Joined Session"

### ISSUE THREAD

**Issue by hanzov69** [Kegbot/kegbot-server#250]
When a user starts a new session and twitter is configured, server will tweet "<user> kicked off a new session" and "<user> joined the session", effectively creating duplicate tweets and spamming the timeline.

Suggest suppressing "<user> joined the session" tweet in the event of a new session.
![screen shot 2014-04-13 at 5 54 28 am](https://cloud.githubusercontent.com/assets/2313928/2689251/d3f19ede-c2f1-11e3-9e3e-ba72af8b45a9.png)

**Comment by mik3y** [comment]
Old issue cleanup: Partially resolved by #363; not planning further action.
