### ISSUE TITLE
Server Error (500) on delete drink - v0.9.30

### ISSUE THREAD

**Issue by KnoAll** [Kegbot/kegbot-server#275]
I am on server version 0.9.30 on RPi/kegberry and when attempting to delete a drink I get an error:
Server Error (500)
This happens after the confirm window appears and i select 'Delete Drink'
This seems to be the case on all drinks I attempt to delete.
There do not appear to be any logs on this. 
All else appears to be working. I am able to re-size the drink as expected.

**Comment by mik3y** [comment]
Cleaning up old/obsolete issues.
