### ISSUE TITLE
Requesting finer granularity over Twitter events

### ISSUE THREAD

**Issue by jlopp** [Kegbot/kegbot-server#282]
There are six different tweet events / templates, but only three toggles for enabling / disabling certain events. It would be great if each event had its own toggle. My problem is that I want to enable the "Session Started" tweet as a generic broadcast to our company that the taps are open, but I do NOT want to enable the "session joined" event because we have hundreds of employees and this would be annoying to fill everyone's twitter feed with.

**Comment by mik3y** [comment]
Fixed in #363
