### ISSUE TITLE
Email notifications point to localhost

### ISSUE THREAD

**Issue by bamBrewing** [Kegbot/kegbot-server#310]
I have my notifications set for all of the settings, but have only been able to test volume low, and new session.

When these notifications come all of the links point to http://localhost. This causes the links to go nowhere unless logged onto the server.

When emails are sent to add users or reset passwords the link uses my dynamic dns hostname.  The links will properly direct the user to the kegbot server from the internet.

**Comment by Meaksplace** [comment]
How do you get to URL settings
