### ISSUE TITLE
Add a "price" field to kegs

### ISSUE THREAD

**Issue by jgustie** [Kegbot/kegbot-server#320]
It would be great if there was a field to track the price of each keg. The system would probably need a default currency setting to support this.

An admin-only "Budget" tab on the stats page would be the stretch feature :)

**Comment by mik3y** [comment]
Bug scrub: cleaning up old issues. Unfortunately no plans to implement this currently. If/when [milestone v1.4](https://github.com/Kegbot/kegbot-server/milestone/5) is implemented, I'd recommend building this as an add-on in terms of the server API.
