### ISSUE TITLE
Migration error v1.1.2 to 1.2.0

### ISSUE THREAD

**Issue by szechyjs** [Kegbot/kegbot-server#325]
I receive the following error during the migration to 1.2.0 when using a postgresql database

`django.db.utils.OperationalError: cannot ALTER TABLE "core_keg" because it has pending trigger events`

Running syndb manually I get some more info,

`Applying core.0002_version_1_2...`

**Comment by szechyjs** [comment]
Have we found a solution for this yet? Perhaps a script that can be run manually to get around this issue. Else a postgresql install is stuck at v1.1.2, unless you reinitialize the database.

**Comment by mik3y** [comment]
I haven't had time to properly research the issue, but on first glance it's either a bug or undocumented behavior of django migrations.

From the [django docs](https://docs.djangoproject.com/en/1.7/topics/migrations/#data-migrations):

> As well as changing the database schema, you can also use migrations to change the data in the ?database itself, in conjunction with the schema if you want.
>
> Migrations that alter data are usually called “data migrations”; they’re best written as separate migrations, sitting alongside your schema migrations.

This language is pretty "soft" and IMO only suggests that decoupling data + schema migrations is a best practice but not a requirement.  (And IIRC South, which it obsoletes, had no such limitation.)

Going back to the error message and suspected rootcause, seems that the migration framework is wrapping all statements belonging to a single migration in a single db transaction, which imo either means (a) the language above should be stronger, or (b) the framework should provide a way to mix these (ie control transaction granularity).

If someone wants to research this with Django, please do!

**Comment by szechyjs** [comment]
Found mention that you can use `db.start_transaction()` and `db.commit_transaction()` in the migration to separate data changes from schema changes.

**Comment by mik3y** [comment]
Excellent! Want to try sprinkling those between the data-altering (`run_python`) statements..?

**Comment by szechyjs** [comment]
It seems that functionality was part of South. I'm trying to figure out how to get it to work with Django 1.7

**Comment by mik3y** [comment]
Issue cleanup: Looks like you solved this locally in cba5b02. Since the troublesome migration is a few years old at this point, and no one else has reported it, I'm going to close/wontfix. And the lesson for next time is, _really_ don't mix data and schema-altering migrations (https://github.com/Kegbot/kegbot-server/issues/325#issuecomment-70025655).
