### ISSUE TITLE
URL Templating For Web Hooks

### ISSUE THREAD

**Issue by georgeh** [Kegbot/kegbot-server#338]
I'd like the ability to use data from the system event to generate the URL for a Web Hook. 

My use case would be (using string.Template format) using the URL: `https://maker.ifttt.com/trigger/$kind/with/key/oHg5SJYRHA0` as a Web Hook to post the event to [IFTTT's Maker Channel](https://ifttt.com/maker); which I could then use to trigger other things, like mobile push notifications or home automation lights. If I hard-coded the "kind" I can't trigger on specific events like `keg_started` while ignoring individual pours or sessions in IFTTT.

I think there could potentially be more use cases for optionally adding payloads to the URL, but being able to integrate with IFTTT adds value for me. Does this sound like a feature you'd accept a PR for or are there any changes I should make?

**Comment by mik3y** [comment]
Hi George! Yes, would definitely accept a PR for this. Python [string templating](https://docs.python.org/2/library/string.html#template-strings) would be a natural thing to use.

**Comment by georgeh** [comment]
Looking a bit closer at [IFTTT's Maker Channel docs](https://maker.ifttt.com/use/abcdefghijklmnopqrstuvwxyz) I think that this might need to be it's own extra to work with that. I thought it could take arbitrary data structures, but it can only take 3 values with the hardcoded keys "value1", "value2" and "value3".

I'm still going to investigate creating an extra to work with IFTTT, but it's not as simple as adding a `string.Template()` call.

**Comment by georgeh** [comment]
I never made any progress on this and now I'm between kegbots, but I did find https://reflector.io/ which can transform webhooks for use with IFTTT.
