### ISSUE TITLE
Make /kegbot run_workers pid file configurable

### ISSUE THREAD

**Issue by theguardian** [Kegbot/kegbot-server#355]
Can't seem to run two instances of kegbot on one server at the same time. The problem is that when running two instances of /kegbot run_workers, both instances want to write to /tmp/kegbot_run_workers.pid. So the second instance to start always fails.

**Comment by mik3y** [comment]
Pass `--pidfile_dir` to the command. You can't rename the pid files, but you can use a different directory for them.
