### ISSUE TITLE
Pillow IOError

### ISSUE THREAD

**Issue by cantbeatl337** [Kegbot/kegbot-server#94]
I had this issue with PIL and also with Pillow.  I get an IO Error saying that the decoder zip is not available.  I posted this over in the forum as well.  This is the error I get when navigating to the webpage.  The server console sees similar results.

IOError at /admin/beerdb/beerimage/

decoder zip not available

Request Method: GET
Request URL: http://127.0.0.1:8000/admin/beerdb/beerimage/
Django Version: 1.4.2
Exception Type: IOError
Exception Value:

decoder zip not available

Exception Location: /home/user/kb/local/lib/python2.7/site-packages/Pillow-1.7.8-py2.7-linux-x86_64.egg/PIL/Image.py in _getdecoder, line 383
Python Executable: /home/user/kb/bin/python
Python Version: 2.7.3
Python Path:

['/home/user/kb/bin',
‘/home/user/kb/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg’,
‘/home/user/kegbot/pykeg/src’,
‘/home/user/kb/local/lib/python2.7/site-packages/foursquare-20120716-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/poster-0.8.1-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/requests-0.14.2-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/django_crispy_forms-1.2.0-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/pytz-2012h-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/django_icanhaz-0.2.1-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/tweepy-1.12-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/django_nose-1.1-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/South-0.7.6-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/python_gflags-2.0-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/pysqlite-2.6.3-py2.7-linux-x86_64.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/pylcdui-0.5.8-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/protobuf-2.4.1-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/PIL-1.1.7-py2.7-linux-x86_64.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/MySQL_python-1.2.4c1-py2.7-linux-x86_64.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/facebook_sdk-0.4.0-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/django_extensions-1.0.1-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/django_socialregistration-0.5.8-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/django_registration-0.8-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/django_imagekit-2.0.2-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/django_autoslug-1.6.1-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/Django-1.4.2-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/kegbot_api-0.1.2-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/kegbot_pyutils-0.1.4-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/httplib2-0.7.7-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/nose-1.2.1-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/mock-1.0.1-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/python_openid-2.2.5-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/oauth2-1.5.211-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/django_appconf-0.5-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/gunicorn-0.16.1-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/distribute-0.6.30-py2.7.egg’,
‘/home/user/kb/local/lib/python2.7/site-packages/Pillow-1.7.8-py2.7-linux-x86_64.egg’,
‘/home/user/kb/lib/python2.7’,
‘/home/user/kb/lib/python2.7/plat-linux2’,
‘/home/user/kb/lib/python2.7/lib-tk’,
‘/home/user/kb/lib/python2.7/lib-old’,
‘/home/user/kb/lib/python2.7/lib-dynload’,
‘/usr/lib/python2.7’,
‘/usr/lib/python2.7/plat-linux2’,
‘/usr/lib/python2.7/lib-tk’,
‘/home/user/kb/local/lib/python2.7/site-packages’,
‘/home/user/kb/lib/python2.7/site-packages’,
‘/home/user/.kegbot’,
‘/etc/kegbot’]

**Comment by theocincotta** [comment]
@cantbeatl337 Did you find a solution for this? I'm having the same problem and `pip uninstall PIL` did not work for me.

**Comment by theocincotta** [comment]
I was able to fix this by added this line to Dockerfile.
ENV LIBRARY_PATH=/lib:/usr/lib
